name: 'IssueOps'
description: 'Automated Issue Triage & Governance as Code. Detect duplicates, flag crashes, and identify Good First Issues.'
author: 'Anmol Sen'
branding:
  icon: 'layers'
  color: 'blue'


inputs:
  gemini_api_key:
    description: 'Google Gemini API Key'
    required: true
  github_token:
    description: 'GitHub Token for applying labels'
    required: true
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args:
    - "action"
